# Generated by Django 4.2.17 on 2025-01-14 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='date updated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='date deleted', null=True)),
                ('state', models.BooleanField(default=True, help_text='status')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='date updated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='date deleted', null=True)),
                ('state', models.BooleanField(default=True, help_text='status')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Form', 'Form'), ('Input', 'Input')], max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_libraries.company')),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DesignSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='date updated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='date deleted', null=True)),
                ('state', models.BooleanField(default=True, help_text='status')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_libraries.company')),
                ('components', models.ManyToManyField(to='design_libraries.component')),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
    ]
