# Generated by Django 4.2.17 on 2025-01-29 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_libraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsystem',
            name='popularity',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='component',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='design_libraries.company'),
        ),
        migrations.AlterField(
            model_name='designsystem',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_systems', to='design_libraries.company'),
        ),
        migrations.AlterField(
            model_name='designsystem',
            name='components',
            field=models.ManyToManyField(related_name='design_systems', to='design_libraries.component'),
        ),
    ]
