# Generated by Django 4.2.17 on 2025-01-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_libraries', '0002_designsystem_popularity_alter_component_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsystem',
            name='is_updated',
            field=models.BooleanField(default=True),
        ),
    ]
