# Generated by Django 4.2.17 on 2025-02-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_libraries', '0003_designsystem_is_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designsystem',
            old_name='description',
            new_name='large_description',
        ),
        migrations.AddField(
            model_name='designsystem',
            name='short_description',
            field=models.TextField(default='Material 3 is the latest version of Google’s open-source design system. Design and build beautiful, usable products with Material 3.'),
        ),
    ]
