# Generated by Django 4.2.17 on 2025-02-08 23:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('design_libraries', '0004_rename_description_designsystem_large_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designsystem',
            name='thumbnail_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='thumbnails/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='designsystem',
            name='short_description',
            field=models.TextField(default='Description here'),
        ),
    ]
