# Generated by Django 4.2.17 on 2025-02-15 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_libraries', '0006_designsystem_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='date updated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='date deleted', null=True)),
                ('state', models.BooleanField(default=True, help_text='status')),
                ('figma', models.URLField(null=True)),
                ('web', models.URLField(null=True)),
                ('storybook', models.URLField(null=True)),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='designsystem',
            name='links',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='design_libraries.link'),
        ),
    ]
