# Generated by Django 4.2.17 on 2025-01-10 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='date updated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='date deleted', null=True)),
                ('state', models.BooleanField(default=True, help_text='status')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('UX Design', 'Ux'), ('UI Design', 'Ui'), ('Product Design', 'Product')], max_length=20)),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='date updated', null=True)),
                ('date_deleted', models.DateTimeField(blank=True, help_text='date deleted', null=True)),
                ('state', models.BooleanField(default=True, help_text='status')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('autor', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('time_to_read', models.IntegerField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
        ),
    ]
