# Generated by Django 4.2.17 on 2025-01-14 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_news_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='status',
            new_name='type',
        ),
    ]
